from typing import Protocol, Optional

from src.domain.user.entities import User, Profile, Posts
from src.infrastructure.db.models import UserPosts

class UserRepositoryProtocol(Protocol):
    async def add_user(self, user: User) -> None: ...
    async def add_profile(self, profile: Profile) -> None: ...
    async def add_post(self, post: Posts) -> None: ...
    async def get_user_post_by_id(self, user_id: str) -> list[UserPosts]: ...